version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  api:
    image: 'api:latest'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '5000:5000'
    depends_on: 
      - redis
  ui:
    image: 'ui:latest'
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5000/
    ports:
      - '3000:3000'
    depends_on: 
      - api